import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BlurTransition from "@/components/BlurTransition";
import Smoothscroll from "@/lib/SmoothScroll";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <Smoothscroll>
          <div className="relative">
            <BlurTransition />
            <header className="sticky top-0 z-50 bg-white rounded-b-xl">
              <Navbar />
            </header>
            {children}
          </div>
        </Smoothscroll>
      </body>
    </html>
  );
}
